version: "3"
services:
    mysql_dev:
        container_name: mysql_dev
        image: 'mysql:latest'
        restart: 'always'
        environment:
          MYSQL_USER: webapplication
          MYSQL_PASSWORD: "cesi"
          MYSQL_DATABASE: videgrenierenligne
          MYSQL_ROOT_PASSWORD: "root"
        ports:
          - '8080:80'
        volumes:
          - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
        
    phpmyadmin_dev:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
          - "8081:80"
        depends_on:
          - mysql_dev
        environment:
          PMA_HOST: mysql_dev
    
    videgrenier_dev:
        image: 'videgrenier'
        ports:
          - '8082:80'
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          ALLOW_OVERRIDE: 'true'
          MYSQL_HOST: mysql_dev
          MYSQL_USER: webapplication
          MYSQL_PASSWORD: "cesi"

        depends_on:
          - mysql_dev

        links: 
          - mysql_dev:mysql


       
        
     