version: "3"
services:
    dbdev:
        container_name: dbdev
        image: 'mysql:latest'
        restart: 'always'
        environment:
          MYSQL_USER: webapplication
          MYSQL_PASSWORD: "cesi"
          MYSQL_DATABASE: videgrenierenligne
          MYSQL_ROOT_PASSWORD: "root"
        ports:
          - '9005:80'
        volumes:
          - mysql_datadev:/var/lib/mysql
          - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

        
    phpmyadmin_dev:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
          - "9002:80"
        depends_on:
          - dbdev
        environment:
          PMA_HOST: dbdev

    
    videgrenier_dev:
        image: 'videgrenier'
        ports:
          - '8081:80'
        build:
          context: .
          dockerfile: Dockerfile
        environment:
          ALLOW_OVERRIDE: 'true'
          # user: "root"
          # db: "mysql_production"
          # password: "root"
          MYSQL_HOST: dbdev
          MYSQL_USER: webapplication
          MYSQL_PASSWORD: "cesi"

        depends_on:
          - dbdev

        links: 
          - dbdev:mysql

        # volumes:
        #   - ./app:/var/www/html

    
volumes:
    mysql_datadev:
      external: true